[package]
name = "buscal"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
nom = "7.1.1"
nom_locate = "4.1.0"
tempfile = "3.20.0"
